### ISSUE TITLE
 Lack of Connectivity Between Bot and Knowledge Base

### ISSUE THREAD

**Issue by SaroashDS** [shahiryar/jcaa-demo#1]
Despite our integration efforts, it has come to our attention that our bot is not currently connected to the knowledge base, hindering the seamless retrieval of relevant information. This issue requires immediate attention to restore functionality and ensure operational efficiency.

**Comment by shahiryar** [comment]
Thank you for highlighting that.
I am on it.
Will keep you posted.

**Comment by shahiryar** [comment]
Done!
Connected the chatbot to the knowledgebase.
